### PR TITLE
15 theme switcher with cookie

### LINKED ISSUE #15: Black Flashes on Page Reloads
Problem probably: Preact theme Switcher JS must be hydrated before theme is finally set, bc. current user theme comes from localstorage. 

=> Idea: Store current user theme in userSession and pass it down on server render. 
=> Idea 2: Add a new Wrapper  in Layout component around header, main and footer components to attach the theme attribute to.

### LINKED ISSUE #32: Moving CSS imports from Layout.tsx to _App.tsx breaks styles
For some reason, the styles of the website are broken (e.g. not loaded at all), 
when the reset.css and postcss/global.css are imported in _App.tsx instead of in Layout.tsx. 
This behavior also persists after completely restarting the dev server.

```ts
// Layout.tsx
export default function Layout(props: LayoutProps) {
  return (
    <>
      {
        /* <Head>
        <title>Audio Logbook</title>
        <link rel="stylesheet" href="/reset.css" />
        <link rel="stylesheet" href="/postcss/global.css" />
      </Head> */
      }
      <header>
        <h1>{(props.h1Override) ? props.h1Override : "Audio Logbook"}</h1>
        <div class="flex-gap"></div>
        {/* TODO: Put Date Seletor here? */}
        <ThemeSwitcher />
        <UserInfo user={props.user} />
      </header>

      <main>
        {props.children}
      </main>

      <footer>
        <pre>Deployment: {DEPLOYMENT_ID}</pre>
      </footer>
    </>
  );
}

```

```ts
// _App.tsx
export default function App({ Component }: AppProps) {
  return (
    <html data-custom="data">
      <Head>
        <title>Audio Logbook</title>
        <link rel="stylesheet" href={asset("reset.css")} />
        <link rel="stylesheet" href="/postcss/global.css" />
      </Head>
      <body class="bodyClass">
        <Component />
      </body>
    </html>
  );
}

```

Bildschirmfoto 2023-04-09 um 20 20 46

### PR DESCRIPTION
**Pull request by bjesuiter**
closes #15 
fixes and closes #32

### CODE REVIEW

**Review by Bloodiko — APPROVED** [review]
Is getThemeOnServer(req:) really needed in every single file ? - 
would it be possible to move this into ctx ? 

Hmm question: 
if i have the following layout: 
```
/_middleware.tsx
/folder1/
/folder1/_middleware.tsx
``` 
Are both middlewares executed before going through the file itself ? 
If yes, i think a global middleware, injecting the Theme might be the way to go here
Tell me what you think about this. 

Otherwise, everything looks fine from my side.

**Comment by bjesuiter** [comment]
AFAIK both middleware's should be called , since they are chainable. 
More complicated is the typing for this context, especially bc fresh is not smart enough to figure out the types as we go and add things to this context, so we have to manually type this out every time. 

But, I also don't like the integration of the theme extraction in every file, so I also prefer a top-level middleware. 

Maybe we can do the following: 
Add a top-level middleware with typing including only the theme variable. 

Then we define the user area context to extend the top level context and add the user field there together with the other fields of this context. 

Only thing then: All Usersrea routes must import the UserareaContext and all outside files must import the ToplevelContext, to have the correct types.

**Comment by bjesuiter** [comment]
@Bloodiko I replaced all occurrences of getThemeOnServer with access to the context, either ToplevelContext or UserareaContext. 

Anything under /userarea has the UserareaContext (includes the user) and 
anything above has the ToplevelContext. 

I think, it's not the most elegant design, but the most practicable in the current state of the fresh framework. 
Please take a look again, whether you think it looks good.

**Comment by bjesuiter** [comment]
@Bloodiko Bump 😀 

Request for 2nd Review on this repo after integrating a new middleware structure for the theme variable

**Review by Bloodiko — APPROVED** [review]
It works, and changes are mostly type adjustments, 
the additions are well documented - undestood what the changes should do or not do (in case of App.tsx
approved

**Pull request merged**
